/**
 * Do not edit this file it is auto-generated by italia-utils / gen-api-models.
 * See https://github.com/teamdigitale/italia-utils
 */
/* tslint:disable */

import * as t from "io-ts";
import { EligibilityCheckSuccessEligible } from "./EligibilityCheckSuccessEligible";
import { EligibilityCheckSuccessIneligible } from "./EligibilityCheckSuccessIneligible";

export const EligibilityCheckSuccess = t.union(
  [EligibilityCheckSuccessEligible, EligibilityCheckSuccessIneligible],
  "EligibilityCheckSuccess"
);

export type EligibilityCheckSuccess = t.TypeOf<typeof EligibilityCheckSuccess>;
