/**
 * Do not edit this file it is auto-generated by italia-utils / gen-api-models.
 * See https://github.com/teamdigitale/italia-utils
 */
/* tslint:disable */

import * as t from "io-ts";
import { EligibilityCheckSuccess } from "./EligibilityCheckSuccess";
import { EligibilityCheckFailure } from "./EligibilityCheckFailure";

/**
 * Eligibility check
 */

export const EligibilityCheck = t.union(
  [EligibilityCheckSuccess, EligibilityCheckFailure],
  "EligibilityCheck"
);

export type EligibilityCheck = t.TypeOf<typeof EligibilityCheck>;
