/**
 * Do not edit this file it is auto-generated by italia-utils / gen-api-models.
 * See https://github.com/teamdigitale/italia-utils
 */
/* tslint:disable */

import * as t from "io-ts";
import { FamilyMember } from "./FamilyMember";

export type FamilyMembers = t.TypeOf<typeof FamilyMembers>;
export const FamilyMembers = t.readonlyArray(
  FamilyMember,
  "array of FamilyMember"
);
