/**
 * Do not edit this file it is auto-generated by italia-utils / gen-api-models.
 * See https://github.com/teamdigitale/italia-utils
 */
/* tslint:disable */

import * as t from "io-ts";
import { NonEmptyString, FiscalCode } from "italia-ts-commons/lib/strings";

export type FamilyMember = t.TypeOf<typeof FamilyMember>;
export const FamilyMember = t.exact(
  t.intersection(
    [
      t.interface({
        name: NonEmptyString,
        surname: NonEmptyString
      }),
      t.partial({
        fiscalCode: FiscalCode
      })
    ],
    "FamilyMember"
  )
);
