/**
 * Do not edit this file it is auto-generated by italia-utils / gen-api-models.
 * See https://github.com/teamdigitale/italia-utils
 */
/* tslint:disable */

import { WithinRangeInteger } from "italia-ts-commons/lib/numbers";
import * as t from "io-ts";

/**
 * Max bonus tax benefit in euro
 */

export type MaxBonusTaxBenefit = t.TypeOf<typeof MaxBonusTaxBenefit>;
export const MaxBonusTaxBenefit = WithinRangeInteger(30, 100);
