/**
 * Do not edit this file it is auto-generated by italia-utils / gen-api-models.
 * See https://github.com/teamdigitale/italia-utils
 */
/* tslint:disable */

import { WithinRangeInteger } from "italia-ts-commons/lib/numbers";
import * as t from "io-ts";

/**
 * Max bonus amount in euro
 */

export type MaxBonusAmount = t.TypeOf<typeof MaxBonusAmount>;
export const MaxBonusAmount = WithinRangeInteger(150, 500);
